-- Supabase migration for shared households, sections, tags, and enhanced inventory
-- Run once in the Supabase SQL editor.

create extension if not exists "pgcrypto";

-- Households
create table if not exists public.households (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  join_code text not null unique,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.household_members (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member',
  created_at timestamptz not null default now(),
  unique (household_id, user_id)
);

-- Profiles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  created_at timestamptz not null default now()
);

-- User settings
create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  dark_mode boolean not null default false,
  auto_mailer boolean not null default false,
  active_household_id uuid references public.households(id) on delete set null,
  low_stock_threshold integer not null default 1,
  alert_days integer not null default 7,
  updated_at timestamptz not null default now()
);

-- Sections (custom per household)
create table if not exists public.sections (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (household_id, name)
);

-- Tag rules (per household tag thresholds)
create table if not exists public.tag_rules (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  tag text not null,
  alert_days integer,
  low_stock_threshold integer,
  created_at timestamptz not null default now(),
  unique (household_id, tag)
);

-- Items
create table if not exists public.items (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  barcode text,
  name text,
  brand text,
  image_url text,
  nutriscore text,
  nutriments jsonb not null default '{}',
  expiry_date date,
  quantity integer not null default 1,
  state text,
  section text,
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Product defaults
create table if not exists public.product_defaults (
  household_id uuid not null references public.households(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  barcode text not null,
  default_section text,
  default_tags text[] not null default '{}',
  last_updated timestamptz not null default now(),
  primary key (household_id, barcode)
);

-- Item history (audit log)
create table if not exists public.item_history (
  id bigint generated by default as identity primary key,
  item_id bigint,
  household_id uuid not null references public.households(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  data jsonb,
  previous_data jsonb,
  created_at timestamptz not null default now()
);

-- Compatibility: ensure columns exist if tables were created earlier
alter table if exists public.items
  add column if not exists household_id uuid references public.households(id) on delete cascade,
  add column if not exists tags text[] not null default '{}',
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.product_defaults
  add column if not exists household_id uuid references public.households(id) on delete cascade,
  add column if not exists default_tags text[] not null default '{}';

alter table if exists public.user_settings
  add column if not exists active_household_id uuid references public.households(id) on delete set null,
  add column if not exists low_stock_threshold integer not null default 1,
  add column if not exists alert_days integer not null default 7;

-- Indexes
create index if not exists items_household_id_idx on public.items (household_id);
create index if not exists items_expiry_date_idx on public.items (expiry_date);
create index if not exists sections_household_id_idx on public.sections (household_id);
create index if not exists tag_rules_household_id_idx on public.tag_rules (household_id);
create index if not exists product_defaults_household_id_idx on public.product_defaults (household_id);
create index if not exists household_members_user_id_idx on public.household_members (user_id);
create index if not exists item_history_household_id_idx on public.item_history (household_id);
create index if not exists item_history_item_id_idx on public.item_history (item_id);

-- RLS
alter table public.profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.households enable row level security;
alter table public.household_members enable row level security;
alter table public.sections enable row level security;
alter table public.tag_rules enable row level security;
alter table public.items enable row level security;
alter table public.product_defaults enable row level security;
alter table public.item_history enable row level security;

-- Helper functions (bypass RLS safely)
create or replace function public.is_household_member(hid uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.household_members hm
    where hm.household_id = hid and hm.user_id = auth.uid()
  );
$$;

create or replace function public.is_household_owner(hid uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.households h
    where h.id = hid and h.created_by = auth.uid()
  )
  or exists (
    select 1 from public.household_members hm
    where hm.household_id = hid and hm.user_id = auth.uid() and hm.role = 'owner'
  );
$$;

create or replace function public.shares_household(target_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.household_members hm_self
    join public.household_members hm_other
      on hm_self.household_id = hm_other.household_id
    where hm_self.user_id = auth.uid()
      and hm_other.user_id = target_user_id
  );
$$;

grant execute on function public.is_household_member(uuid) to authenticated;
grant execute on function public.is_household_owner(uuid) to authenticated;
grant execute on function public.shares_household(uuid) to authenticated;

-- Profiles policies
drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;

create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id or public.shares_household(id));

create policy "profiles_insert_own" on public.profiles
  for insert with check (auth.uid() = id);

create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

-- User settings policies
drop policy if exists "settings_select_own" on public.user_settings;
drop policy if exists "settings_insert_own" on public.user_settings;
drop policy if exists "settings_update_own" on public.user_settings;
drop policy if exists "settings_delete_own" on public.user_settings;

create policy "settings_select_own" on public.user_settings
  for select using (auth.uid() = user_id);

create policy "settings_insert_own" on public.user_settings
  for insert with check (auth.uid() = user_id);

create policy "settings_update_own" on public.user_settings
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "settings_delete_own" on public.user_settings
  for delete using (auth.uid() = user_id);

-- Households policies
drop policy if exists "households_select_member" on public.households;
drop policy if exists "households_insert_owner" on public.households;
drop policy if exists "households_update_owner" on public.households;
drop policy if exists "households_delete_owner" on public.households;

create policy "households_select_member" on public.households
  for select using (public.is_household_member(households.id));

create policy "households_insert_owner" on public.households
  for insert with check (created_by = auth.uid());

create policy "households_update_owner" on public.households
  for update using (public.is_household_owner(households.id))
  with check (public.is_household_owner(households.id));

create policy "households_delete_owner" on public.households
  for delete using (public.is_household_owner(households.id));

-- Household members policies
drop policy if exists "household_members_select_member" on public.household_members;
drop policy if exists "household_members_insert_owner" on public.household_members;
drop policy if exists "household_members_delete_self_or_owner" on public.household_members;

create policy "household_members_select_member" on public.household_members
  for select using (
    household_members.user_id = auth.uid()
    or public.is_household_owner(household_members.household_id)
  );

create policy "household_members_insert_owner" on public.household_members
  for insert with check (public.is_household_owner(household_members.household_id));

create policy "household_members_delete_self_or_owner" on public.household_members
  for delete using (
    household_members.user_id = auth.uid()
    or public.is_household_owner(household_members.household_id)
  );

-- Sections policies
drop policy if exists "sections_select_member" on public.sections;
drop policy if exists "sections_insert_member" on public.sections;
drop policy if exists "sections_update_member" on public.sections;
drop policy if exists "sections_delete_member" on public.sections;

create policy "sections_select_member" on public.sections
  for select using (public.is_household_member(sections.household_id));

create policy "sections_insert_member" on public.sections
  for insert with check (public.is_household_member(sections.household_id));

create policy "sections_update_member" on public.sections
  for update using (public.is_household_member(sections.household_id))
  with check (public.is_household_member(sections.household_id));

create policy "sections_delete_member" on public.sections
  for delete using (public.is_household_member(sections.household_id));

-- Tag rules policies
drop policy if exists "tag_rules_select_member" on public.tag_rules;
drop policy if exists "tag_rules_insert_member" on public.tag_rules;
drop policy if exists "tag_rules_update_member" on public.tag_rules;
drop policy if exists "tag_rules_delete_member" on public.tag_rules;

create policy "tag_rules_select_member" on public.tag_rules
  for select using (public.is_household_member(tag_rules.household_id));

create policy "tag_rules_insert_member" on public.tag_rules
  for insert with check (public.is_household_member(tag_rules.household_id));

create policy "tag_rules_update_member" on public.tag_rules
  for update using (public.is_household_member(tag_rules.household_id))
  with check (public.is_household_member(tag_rules.household_id));

create policy "tag_rules_delete_member" on public.tag_rules
  for delete using (public.is_household_member(tag_rules.household_id));

-- Items policies
drop policy if exists "items_select_member" on public.items;
drop policy if exists "items_insert_member" on public.items;
drop policy if exists "items_update_member" on public.items;
drop policy if exists "items_delete_member" on public.items;

create policy "items_select_member" on public.items
  for select using (public.is_household_member(items.household_id));

create policy "items_insert_member" on public.items
  for insert with check (
    user_id = auth.uid()
    and public.is_household_member(items.household_id)
  );

create policy "items_update_member" on public.items
  for update using (public.is_household_member(items.household_id))
  with check (public.is_household_member(items.household_id));

create policy "items_delete_member" on public.items
  for delete using (public.is_household_member(items.household_id));

-- Product defaults policies
drop policy if exists "product_defaults_select_member" on public.product_defaults;
drop policy if exists "product_defaults_insert_member" on public.product_defaults;
drop policy if exists "product_defaults_update_member" on public.product_defaults;
drop policy if exists "product_defaults_delete_member" on public.product_defaults;

create policy "product_defaults_select_member" on public.product_defaults
  for select using (public.is_household_member(product_defaults.household_id));

create policy "product_defaults_insert_member" on public.product_defaults
  for insert with check (public.is_household_member(product_defaults.household_id));

create policy "product_defaults_update_member" on public.product_defaults
  for update using (public.is_household_member(product_defaults.household_id))
  with check (public.is_household_member(product_defaults.household_id));

create policy "product_defaults_delete_member" on public.product_defaults
  for delete using (public.is_household_member(product_defaults.household_id));

-- Item history policies
drop policy if exists "item_history_select_member" on public.item_history;
drop policy if exists "item_history_insert_member" on public.item_history;

create policy "item_history_select_member" on public.item_history
  for select using (public.is_household_member(item_history.household_id));

create policy "item_history_insert_member" on public.item_history
  for insert with check (public.is_household_member(item_history.household_id));

-- Item history trigger
create or replace function public.log_item_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
begin
  v_user_id := coalesce(auth.uid(), NEW.user_id, OLD.user_id);

  if (TG_OP = 'INSERT') then
    insert into public.item_history (item_id, household_id, user_id, action, data)
    values (NEW.id, NEW.household_id, v_user_id, 'created', to_jsonb(NEW));
    return NEW;
  elsif (TG_OP = 'UPDATE') then
    insert into public.item_history (item_id, household_id, user_id, action, data, previous_data)
    values (NEW.id, NEW.household_id, v_user_id, 'updated', to_jsonb(NEW), to_jsonb(OLD));
    return NEW;
  elsif (TG_OP = 'DELETE') then
    insert into public.item_history (item_id, household_id, user_id, action, data)
    values (OLD.id, OLD.household_id, v_user_id, 'deleted', to_jsonb(OLD));
    return OLD;
  end if;

  return null;
end;
$$;

drop trigger if exists items_history_trigger on public.items;
create trigger items_history_trigger
after insert or update or delete on public.items
for each row execute function public.log_item_change();

-- Join household RPC (security definer)
create or replace function public.join_household(join_code text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_household_id uuid;
begin
  select id into v_household_id from public.households where households.join_code = join_code;
  if v_household_id is null then
    raise exception 'Invalid join code';
  end if;

  insert into public.household_members (household_id, user_id, role)
  values (v_household_id, auth.uid(), 'member')
  on conflict do nothing;

  return v_household_id;
end;
$$;

-- Create household RPC (security definer)
create or replace function public.create_household(household_name text, join_code text)
returns public.households
language plpgsql
security definer
set search_path = public
as $$
declare
  v_household public.households;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  insert into public.households (name, join_code, created_by)
  values (household_name, join_code, auth.uid())
  returning * into v_household;

  insert into public.household_members (household_id, user_id, role)
  values (v_household.id, auth.uid(), 'owner')
  on conflict do nothing;

  insert into public.user_settings (user_id, active_household_id)
  values (auth.uid(), v_household.id)
  on conflict (user_id)
  do update set active_household_id = excluded.active_household_id;

  return v_household;
end;
$$;

grant execute on function public.join_household(text) to authenticated;
grant execute on function public.create_household(text, text) to authenticated;
